# This is the CD pipeline to deploy  Office Hours API
name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

# manual trigger
trigger: none

variables:
- template: ./yaml-templates/variables.yaml

stages:
- stage: Build
  displayName: 'Build App'
  condition: and(succeeded(), eq(variables.isMain, 'true')) 
  pool:
    name: 'Default-Test'
  jobs:
  - job: Build
    displayName: 'Build Office Hours API'
    steps:
    - task: UseDotNet@2
      displayName: 'Download .NET'
      inputs:
        packageType: sdk
        version: 6.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - template: '/${{variables.yamlTemplateLoc}}/build-dotnet-app.yaml'
      parameters:
        displayAppName: $(webAppName)
        solution: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(webAppName)/$(webAppName).csproj'
        testProject: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(webAppName).UnitTests/$(webAppName).UnitTests.csproj'
        artifactName: $(webAppName)

    - template: '/${{variables.yamlTemplateLoc}}/build-dotnet-app.yaml'
      parameters:
        displayAppName: $(batchAppName)
        solution: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(batchAppName)/$(batchAppName).csproj'
        artifactName: $(batchAppName)

- stage: Test_Deploy
  displayName: 'Deploy to Test'
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  pool:
    name: 'Default-Test'
  variables:
    targetEnv: 'test'
  jobs:
  - template: '/${{variables.yamlTemplateLoc}}/deploy-web-app.yaml'
    parameters:
      stageName: 'WebApp'
      targetEnv: ${{variables.targetEnv}}
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.webAppName}}
      artifactName: $(webAppName)
      serviceConnection: '${{variables.serviceConn}}-${{variables.targetEnv}}'
      azureAppName: $(azureWebAppName)

  - template: '/${{variables.yamlTemplateLoc}}/deploy-func-app.yaml'
    parameters:
      stageName: 'BatchJob'
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.batchAppName}}
      targetEnv: ${{variables.targetEnv}}
      artifactName: $(batchAppName)
      serviceConnection: '${{variables.serviceConn}}-${{variables.targetEnv}}'
      azureFuncName: $(azureFuncAppName)
      functionAppType: 'functionAppLinux'

- stage: Prod_Deploy
  displayName: 'Deploy to Prod'
  condition: and(succeeded(), eq(variables.isMain, 'true')) 
  pool:
    name: 'Default-Prod'
  variables:
    targetEnv: 'prod'
  jobs:
  - template: '/${{variables.yamlTemplateLoc}}/deploy-web-app.yaml'
    parameters:
      stageName: 'WebApp'
      targetEnv: ${{variables.targetEnv}}
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.webAppName}}
      artifactName: $(webAppName)
      serviceConnection: '${{variables.serviceConn}}-${{variables.targetEnv}}'
      azureAppName: $(azureWebAppName)

  - template: '/${{variables.yamlTemplateLoc}}/deploy-func-app.yaml'
    parameters:
      stageName: 'BatchJob'
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.batchAppName}}
      targetEnv: ${{variables.targetEnv}}
      artifactName: $(batchAppName)
      serviceConnection: '${{variables.serviceConn}}-${{variables.targetEnv}}'
      azureFuncName: $(azureFuncAppName)
      functionAppType: 'functionAppLinux'
