# This is the CD pipeline for provisioning Azure Serivce to host Invest solution
name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

# manual trigger
trigger: none

variables:
- template: ./yaml-templates/variables.yaml
- name: targetEnv
  value: dev
- name: azureServiceConn
  value: '${{variables.serviceConn}}-dev'

pool: 'Default-Dev'

stages:
- stage: Build
  displayName: 'Build IaC and App'
  jobs:
  - job: Build
    displayName: 'Build Batch Job'
    steps:
    - task: UseDotNet@2
      displayName: 'Download .NET'
      inputs:
        packageType: sdk
        version: 6.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - template: '/${{variables.yamlTemplateLoc}}/create-infra-package.yaml'
      parameters:
        resourceGroupName: $(resourceGroupName)
        artifactName: $(artifactName)
        deploymentFolder: $(deploymentFolder)

    - template: '/${{variables.yamlTemplateLoc}}/build-dotnet-app.yaml'
      parameters:
        displayAppName: $(webAppName)
        solution: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(webAppName)/$(webAppName).csproj'
        testProject: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(webAppName).UnitTests/$(webAppName).UnitTests.csproj'
        artifactName: $(webAppName)

    - template: '/${{variables.yamlTemplateLoc}}/build-dotnet-app.yaml'
      parameters:
        displayAppName: $(batchAppName)
        solution: '$(Build.SourcesDirectory)/$(recipeName)/development/$(projectFolder)/$(batchAppName)/$(batchAppName).csproj'
        artifactName: $(batchAppName)
        
- stage: Dev_Infra
  displayName: 'Provision to DEV'
  jobs:
  - template: '/${{variables.yamlTemplateLoc}}/provision-infra.yaml'
    parameters:
      deployArtifact: $(artifactName)
      resourceGroupName: $(resourceGroupName)
      targetEnv: ${{variables.targetEnv}}
      serviceConnection: ${{variables.azureServiceConn}}
      keyVaultName: $(keyVaultName)

- stage: Dev_App
  displayName: 'Deploy to DEV'
  jobs:
  - template: '/${{variables.yamlTemplateLoc}}/deploy-web-app.yaml'
    parameters:
      stageName: 'WebApp'
      targetEnv: ${{variables.targetEnv}}
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.webAppName}}
      artifactName: $(webAppName)
      serviceConnection: ${{variables.azureServiceConn}}
      azureAppName: $(azureWebAppName)

  - template: '/${{variables.yamlTemplateLoc}}/deploy-func-app.yaml'
    parameters:
      stageName: 'BatchJob'
      resourceGroupName: $(resourceGroupName)
      displayAppName: ${{variables.batchAppName}}
      targetEnv: ${{variables.targetEnv}}
      artifactName: $(batchAppName)
      serviceConnection: ${{variables.azureServiceConn}}
      azureFuncName: '$(azureFuncAppName)'
      functionAppType: 'functionAppLinux'

