# This is a shared module for CD: Deploying Web App or API App into App Services
parameters:
  - name: resourceGroupName 
    displayName: 'Target resource group without envrionment suffix'
    type: string
  # Valid names may only contain alphanumeric characters and '_' and may not start with a number.
  - name: stageName 
    displayName: 'Text for stage name'
    type: string
  # use for labeling the stage, should be aplhanumeric only
  - name: displayAppName 
    displayName: 'Text for display name'
    type: string
  - name: artifactName 
    displayName: 'Name of the deployable package'
    type: string
  - name: azureAppName
    displayName: 'Azure Web App name without envrionment suffix'
    type: string
  - name: targetEnv 
    displayName: 'Predefined target environment'
    type: string
    default: dev
    values:
    - dev
    - test
    - prod
  - name: serviceConnection
    displayName: 'Name of Azure DevOps Service Connection used for deployment'
    type: string
  - name: scmAccessRequired
    displayName: 'Indicate if SCM firewall needs to open/close'
    type: boolean
    default: false

jobs:
- deployment: 'Deploy_${{parameters.stageName}}'
  displayName: ${{parameters.displayAppName}}
  variables:
    targetEnvName: ${{upper(parameters.targetEnv)}}
    rg-full-name: '${{parameters.resourceGroupName}}-${{parameters.targetEnv}}'
    app-full-name: '${{parameters.azureAppName}}-${{parameters.targetEnv}}'
  environment: ${{variables.targetEnvName}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact'
          inputs:
            artifact: ${{parameters.artifactName}}
            path: $(Build.SourcesDirectory)/drop

        - task: AzureCLI@2
          displayName: 'Enable SCM access (${{variables.targetEnvName}})'
          condition: ${{parameters.scmAccessRequired}}
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              $agentIP = (New-Object net.webclient).downloadstring("https://api.ipify.org")
              az webapp config access-restriction add --resource-group $(rg-full-name) --name $(app-full-name) `
                --rule-name build_server --action Allow --ip-address "$agentIP/32" --priority 250 --scm-site true

        - task: AzureWebApp@1 
          displayName: Deploy ${{parameters.displayAppName}} to ${{parameters.targetEnv}}
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            appName: $(app-full-name)
            package: $(Build.SourcesDirectory)/drop/**/${{parameters.artifactName}}.zip

        - task: AzureCLI@2
          displayName: 'Disable SCM access (${{variables.targetEnvName}})'
          condition: ${{parameters.scmAccessRequired}}
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              $agentIP = (New-Object net.webclient).downloadstring("https://api.ipify.org")
              az webapp config access-restriction remove --resource-group $(rg-full-name) --name $(app-full-name) `
                --rule-name build_server --scm-site true