parameters:
  - name: deployArtifact 
    displayName: 'Name of the artifact for provisioning'
    type: string
  - name: resourceGroupName 
    displayName: 'Target resource group without suffix'
    type: string
  - name: targetEnv
    displayName: 'Target environment (dev/test/prod)'
    type: string
    values:
    - dev
    - test
    - prod
  - name: serviceConnection
    displayName: 'Name of Service Connection for deployment'
    type: string

jobs:
- deployment: Provision_Infrastructure
  displayName: Provision Infrastructure
  variables:
    rg-full-name: '${{parameters.resourceGroupName}}-${{parameters.targetEnv}}'
    targetEnvName: ${{upper(parameters.targetEnv)}}
  environment: ${{variables.targetEnvName}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        - download: current
          displayName: 'Download Artifact'
          artifact: ${{parameters.deployArtifact}}
        - task: AzureCLI@2
          displayName: 'Provision Services (${{variables.targetEnvName}})'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group create --resource-group $(rg-full-name) --name 'main-$(Build.BuildNumber)' `
                --template-file '$(Agent.BuildDirectory)/${{parameters.deployArtifact}}/resource-groups/${{parameters.resourceGroupName}}/main.bicep' `
                --parameters '$(Agent.BuildDirectory)/${{parameters.deployArtifact}}/resource-groups/${{parameters.resourceGroupName}}/main-param-${{parameters.targetEnv}}.json' `
                --parameters environmentName='${{parameters.targetEnv}}' 