# This is a shared module for CD: Deploying ADF artifacts into ADF
parameters:
  - name: resourceGroupName 
    displayName: 'Target resource group without envrionment suffix'
    type: string
  # Valid names may only contain alphanumeric characters and '_' and may not start with a number.
  - name: stageName 
    displayName: 'Text for stage name'
    type: string
  - name: targetEnv 
    type: string
    default: dev
    values:
    - dev
    - test
    - prod
  - name: artifactName 
    type: string
  - name: serviceConnection
    type: string
  - name: adfName
    displayName: 'ADF name without envrionment suffix'
    type: string

jobs:
- deployment: Deploy_App
  displayName: Deploy App
  variables:
    targetEnvName: ${{upper(parameters.targetEnv)}}
    rg-full-name: '${{parameters.resourceGroupName}}-${{parameters.targetEnv}}'
    adf-full-name: '${{parameters.adfName}}-${{parameters.targetEnv}}'
    armTemplatePath: '$(Build.SourcesDirectory)/${{parameters.artifactName}}'
  environment: ${{variables.targetEnvName}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact'
          inputs:
            artifact: ${{parameters.artifactName}}
            path: $(armTemplatePath)

        - task: AzurePowerShell@5
          displayName: 'Stop ADF triggers'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            ScriptType: 'FilePath'
            ScriptPath: $(armTemplatePath)/PrePostDeploymentScript.Ver2.ps1
            ScriptArguments:  -armTemplate "$(armTemplatePath)/ARMTemplateForFactory.json" 
                              -ResourceGroupName "$(rg-full-name)" 
                              -DataFactoryName "$(adf-full-name)" 
                              -predeployment $true 
                              -deleteDeployment $false
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true

        - task: AzureCLI@2
          displayName: 'Deploy ADF (${{variables.targetEnvName}})'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group create --resource-group $(rg-full-name) --name 'main-$(Build.BuildNumber)' `
                --template-file '$(armTemplatePath)/ARMTemplateForFactory.json' `
                --parameters '$(armTemplatePath)/adf-param-files/adf-param-${{parameters.targetEnv}}.json'

        - task: AzureCLI@2
          displayName: 'Approve Private Endpoint (${{variables.targetEnvName}})'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: '$(armTemplatePath)/private-endpoint-approval.ps1'
            workingDirectory: '$(armTemplatePath)/adf-param-files'
            arguments: 
              -targetEnv ${{parameters.targetEnv}}
              -resourceGroupName '$(rg-full-name)' 

        - task: AzurePowerShell@5
          displayName: 'Start ADF triggers'
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            ScriptType: 'FilePath'
            ScriptPath: '$(armTemplatePath)/PrePostDeploymentScript.Ver2.ps1'
            ScriptArguments:  -armTemplate "$(armTemplatePath)/ARMTemplateForFactory.json" 
                              -ResourceGroupName "$(rg-full-name)" 
                              -DataFactoryName "$(adf-full-name)" 
                              -predeployment $false 
                              -deleteDeployment $false
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
